# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5dcce3c29d758dd328482f9d7294b29f92c888ff310296e7712e1382daab01580e9981ac8e1e4accbb5222f5ffebec1290407ca92f0d57d8f17fdfb66ab3fbfc

test:
  secret_key_base: 21f8841d3ad88a513f2933ec12e7d06b1d892bb2525406a2d02ec10171d4a29fa3305d26e3f88b8de281654e7dd061ef0677e80e19d199ee0e6ce3f55b4af718

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
